env = SConscript('godot-cpp/SConstruct')

env.Append(CPPPATH=["src", "MainMenuController", "ButtonController"])

src= Glob("src/*.cpp")

libpath = '../libtest{}{}'.format(env['suffix'], env['SHLIBSUFFIX'])
sharedlib = env.SharedLibrary(libpath, src)
Default(sharedlib)
